services:
  kitsurai:
    build: .
    image: kitsurai
    command: /app/kitsurai --peers dns:kitsurai:3000
    scale: 5
    volumes:
      - ./shared:/app/shared
    develop:
      watch:
        - action: rebuild
          path: .
